name: CaptureTheFlag
main: CalvinMinecraft33\CTF
author: CalvinMinecraft33
version: 1.1.0
api: 
- 1.0.0
- 1.1.0
- 2.0.0

commands:
    ctf:
        usage: /ctf <Create>
        description: Make a game
    ctfstart:
        usage: /ctfstart
        description: start a game
        